apiVersion: v1
kind: Secret
metadata:
  name: nexus-repo-creds
  namespace: argocd
  labels:
    # Label này bắt buộc ArgoCD nhận diện mẫu xác thực chung
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  # Áp dụng cho TẤT CẢ các kho có đường dẫn bắt đầu bằng chuỗi này
  url: "http://nexus3-service.nexus.svc.cluster.local:8081/repository/"
  username: "admin"
  password: "tranmanh12"
