apiVersion: v2
name: app-service-a
description: Helm chart cho Service A sử dụng template chung từ GitHub
version: 1.0.0
dependencies:
  - name: my-app-chart # Tên bộ Helm Chart template chung
    version: 1.0.0 # Phiên bản Helm Chart template
    repository: http://nexus3-service:8081/repository/helm-template/
